# Generated by Django 4.2.7 on 2024-02-16 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_depositmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='depositmodel',
            old_name='accounts',
            new_name='account',
        ),
    ]
